protected/controllers/GroupsController.php
<?php

class GroupsController extends Controller
{
	/**
	 * Use the appropriate layout
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		// Note: finer grained access control wrt profile/contact details/avatar/ssh key/password changing is done at action level
		return array(
			array('allow',  // Everyone who is authenticated may list people and view them (including avatars)
				'actions' => array('index', 'view', 'edit', 'removeMember', 'addMember'),
				'users' => array('@'),
			),
			array('allow', // Creating and Deleting is for Sysadmins only
				'actions' => array('create', 'delete'),
				'roles' => array('sysadmins'),
			),
			array('deny',  // If not permitted above - access is denied...
				'users' => array('*'),
			),
		);
	}

	/**
	 * Show the list of groups
	 */
	public function actionIndex()
	{
		// Create the model instance we will be using for searches....
		$model = new Group('search');
		if( isset($_GET['Group']) ) {
			$model->attributes = $_GET['Group'];
		}

		// Prepare the data provider - and apply a filter to it to ensure filters are applied
		$dataProvider = new SLdapDataProvider($model, array('pagination' => array('pageSize' => 50)));
		$dataProvider->setFilterByModel($model, array('cn', 'description'));
		$dataProvider->setAttributesToLoad( array('cn', 'description') );

		$this->render('index', array(
			'dataProvider' => $dataProvider,
			'model' => $model,
		));
	}

	/**
	 * Create a new group
	 */
	public function actionCreate()
	{
		$model = new Group;

		// Are we attempting to perform the create action?
		if( isset($_POST['Group']) ) {
			// Assign the attributes
			$model->attributes = $_POST['Group'];

			// Set the new group DN
			$filter = Net_LDAP2_Filter::create('ou', 'equals', 'groups');
			$parent = OrganisationalUnit::model()->findFirstByFilter( $filter );
			$model->setDnByParent($parent);

			// Create the new group
			if( $model->save() ) {
				Yii::app()->user->setFlash('success', 'Group created successfully.' );
				$this->redirect(array('view', 'cn' => $model->cn));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Show a list of the group members
	 */
	public function actionView($cn)
	{
		// Load the group we are displaying here...
		$model = $this->loadModel($cn);

		// Create a data provider
		$filter = Net_LDAP2_Filter::create('groupMember', 'equals', $model->cn);
		$dataProvider = $this->createUserSearchProvider($filter);
		$dataProvider->retrieveLimit = 500;

		$this->render('view', array(
			'model' => $model,
			'dataProvider' => $dataProvider,
		));
	}

	/**
	 * Allow the internal and user-visible group name to be changed
	 */
	public function actionEdit($cn)
	{
		$model = $this->loadModel($cn);
		$model->setScenario('edit');

		if( !Yii::app()->user->checkAccess('manageGroup', array('group' => $model)) ) {
			throw new CHttpException(403, 'You are not permitted to change this group.');
		}

		if( isset($_POST['Group']) ) {
			// Update all attributes...
			$model->attributes = $_POST['Group'];
			$model->setDnByParent( $model->getParentDn() );
			if( $model->save() ) {
				Yii::app()->user->setFlash('success', 'Group details updated successfully.');
				$this->redirect( array('view', 'cn' => $model->cn) );
			}
		}

		$this->render('edit', array(
			'model' => $model,
		));
	}

	/**
	 * Delete a group
	 */
	public function actionDelete($cn)
	{
		$model = $this->loadModel($cn);
		$model->setScenario('delete');

		if( isset($_POST['confirmDeletion']) && isset($_POST['deleteGroup']) ) {
			if( $model->delete() ) {
				Yii::app()->user->setFlash('success', 'Group deleted successfully.');
				$this->redirect( array('index') );
			}
		}

		$this->render('delete', array(
			'model' => $model,
		));
	}

	/**
	 * Add a new member to a group
	 */
	public function actionAddMember($cn)
	{
		$model = $this->loadModel($cn);
		$model->setScenario('addMember');

		if( !Yii::app()->user->checkAccess('manageGroup', array('group' => $model)) ) {
			throw new CHttpException(403, 'You are not permitted to change this group.');
		}

		// Maybe we need to add people to the group?
		if( isset($_POST['selectedPerson']) ) {
			$this->processMemberAdd( $model, $_POST['selectedPerson'][0] );
		}

		// Create a data provider
		$filter = Net_LDAP2_Filter::create('groupMember', 'equals', $model->cn);
		$filter = Net_LDAP2_Filter::combine('not', $filter);
		$dataProvider = $this->createUserSearchProvider($filter);

		$this->render('addMember', array(
			'model' => $model,
			'dataProvider' => $dataProvider,
		));
	}

	public function actionRemoveMember($cn)
	{
		$model = $this->loadModel($cn);
		$model->setScenario('removeMember');

		if( !Yii::app()->user->checkAccess('manageGroup', array('group' => $model)) ) {
			throw new CHttpException(403, 'You are not permitted to change this group.');
		}

		// Make sure this is a valid request....
		if( !isset($_POST['selectedPerson']) ) {
			throw new CHttpException(400, 'Invalid request - manipulation prohibited.');
		}

		// Load the member we will be working with
		$member = User::model()->findByDn( $_POST['selectedPerson'][0] );
		if( is_null($member) ) {
			throw new CHttpException(400, 'Invalid request - could not locate the member whose removal has been requested.');
		}

		// Has the removal been confirmed?
		if( isset($_POST['confirmRemoval']) ) {
			$model->removeMember($member);
			if( $model->save() && $member->save() ) {
				Yii::app()->user->setFlash('success', sprintf('%s removed from group successfully.', $member->cn) );
				$this->redirect(array('view', 'cn' => $model->cn));
			}
		}

		$this->render('removeMember', array(
			'model' => $model,
			'member' => $member,
		));
	}

	/**
	 * Retrieve the group specified by $cn from the LDAP Server
	 */
	protected function loadModel($cn, $attributes = array())
	{
		$filter = Net_LDAP2_Filter::create('cn', 'equals', $cn);
		$entry = Group::model()->findFirstByFilter($filter, $attributes);
		if($entry === null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $entry;
	}

	/**
	 * Generate a Menu for one of the Model based views.
	 */
	protected function generateMenu($model)
	{
		$menu = array();
		$params = array('group' => $model);
		// General actions first..
		if( $this->action->id != 'view' ) {
			$menu[] = array('label' => 'View Group', 'url' => array('view', 'cn' => $model->cn));
		}
		// Group management actions...
		if( Yii::app()->user->checkAccess('manageGroup', $params) && $this->action->id != 'edit' ) {
			$menu[] = array('label' => 'Edit Group', 'url' => array('edit', 'cn' => $model->cn));
		}
		if( Yii::app()->user->checkAccess('manageGroup', $params) && $this->action->id != 'addMember' ) {
			$menu[] = array('label' => 'Add Member', 'url' => array('addMember', 'cn' => $model->cn));
		}
		// Sysadmin only actions now
		if( Yii::app()->user->checkAccess('sysadmins') && $this->action->id != 'delete' ) {
			$menu[] = array('label' => 'Delete Group', 'url' => array('delete', 'cn' => $model->cn));
		}
		// Return results
		return $menu;
	}

	/**
	 * Create a Data Provider, configured with a User model for searching purposes
	 */
	protected function createUserSearchProvider( $filter )
	{
		// Create the model instance we will be using for searches....
		$user = new User('search');
		if( isset($_GET['User']) ) {
			$user->attributes = $_GET['User'];
		}

		// Create a data provider
		$dataProvider = new SLdapDataProvider($user);
		$dataProvider->setAttributesToLoad( array('uid', 'cn', 'mail', 'memberStatus') );

		// Setup filters on the data provider - to provide their requested filters + the search done by the user
		$dataProvider->setFilter($filter);
		$dataProvider->setFilterByModel($user, array('uid', 'cn', 'mail', 'memberStatus'));

		return $dataProvider;
	}

	/**
	 * Handle the addition of users to a group
	 */
	protected function processMemberAdd( $group, $userDn )
	{
		// Take the proposed candidate - and turn it into a valid user instance
		$selectedUser = User::model()->findByDn( $userDn );
		if( !$selectedUser instanceof User ) {
			return false;
		}

		// Add them into the given group
		$group->addMember( $selectedUser );
		if( $group->save() && $selectedUser->save() ) {
			Yii::app()->user->setFlash('success', sprintf('%s added to group successfully.', $selectedUser->cn) );
			$this->redirect(array('view', 'cn' => $group->cn));
			return true;
		}
		return false;
	}
};

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span12">
	<?php echo $content; ?>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="page" class="span10">
	<div>
		<?php
			foreach(Yii::app()->user->getFlashes() as $key => $message) {
				echo CHtml::tag('div', array('class' => 'alert alert-' . $key), CHtml::encode($message));
			}
		?>
		<?php echo $content; ?>
	</div>
</div>
<div class="span2 no-print">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'<h3>Operations</h3><hr/>',
		));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->menu,
				'htmlOptions'=>array('class'=>'nav Neverland'),
				'linkLabelWrapper' => 'h5',
			));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="Ben Cooksley">

	<?php
	/* Stylesheet files for Neverland */
	Yii::app()->clientScript->registerCssFile('//cdn.kde.org/css/bootstrap.css');
	Yii::app()->clientScript->registerCssFile('//cdn.kde.org/css/bootstrap-responsive.css');
	Yii::app()->clientScript->registerCssFile('//cdn.kde.org/css/bootstrap-solena.css');

	/* Javascript files */
	Yii::app()->clientScript->registerCoreScript('jquery');
	Yii::app()->clientScript->registerScriptFile("//cdn.kde.org/js/bootstrap.js", CClientScript::POS_END);
	Yii::app()->clientScript->registerScriptFile("//cdn.kde.org/js/bootstrap-neverland.js", CClientScript::POS_END);
	Yii::app()->clientScript->registerScriptFile("//cdn.kde.org/nav/global-nav.js", CClientScript::POS_END);
	?>

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	
	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/img/favicon.ico">
</head>

<body data-spy="scroll">
	<div id="header" class="navbar navbar-static-top Neverland">
		<div class="navbar-inner">
			<div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
				<a class="brand" href="<?php echo Yii::app()->controller->createUrl('/site/index'); ?>">
					<img src="//cdn.kde.org/img/logo.plain.small.png" alt="Home"/>
					KDE Identity
				</a>
				<div class="nav-collapse">
					<div class="nav pull-right">
					<?php $this->widget('application.components.NeverMenu',array(
						'items'=>array(
							array('label' => 'People', 'url' => array('/people/index'), 'glyphIcon' => 'user'),
							array('label' => 'Groups', 'url' => array('/groups/index'), 'glyphIcon' => 'th-list'),
							array('label' => 'Registrations', 'url' => array('/registration/list'), 'glyphIcon' => 'pencil', 'visible' => Yii::app()->user->checkAccess('sysadmins')),
							array('label' => 'Developer Applications', 'url' => array('/developerApplication/list'), 'glyphIcon' => 'file', 'visible' => Yii::app()->user->checkAccess('sysadmins')),
							array('label' => 'Apply for Developer Access', 'url' => array('/developerApplication'), 'glyphIcon' => 'file', 'visible' => Yii::app()->user->checkAccess('users')),
							array('label' => 'Privacy Policy', 'url' => 'https://kde.org/privacypolicy.php', 'glyphIcon' => 'flag'),
							array('label' => 'My Account', 'url' => array('/people/view', 'uid' => Yii::app()->user->id), 'glyphIcon' => 'user', 'visible' => !Yii::app()->user->isGuest),
							array('label' => 'Login', 'url'=>array('/site/login'), 'glyphIcon' => 'cog', 'visible' => Yii::app()->user->isGuest),
							array('label' => 'Register', 'url'=>array('/registration/index'), 'glyphIcon' => 'pencil', 'visible' => Yii::app()->user->isGuest),
							array('label' => 'Logout ('.Yii::app()->user->name.')', 'url' => array('/site/logout'), 'glyphIcon' => 'remove-sign', 'visible' => !Yii::app()->user->isGuest)
						),
						'htmlOptions' => array('class'=>'nav'),
						)); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div id="pageRow" class="container">
		<div class="row">
			<?php echo $content; ?>
			<div class="clearfix"></div>
		</div>
		<div id="footerRow" class="no-print">
			<div class="navbar navbar-bottom Neverland">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
							<li>
							<?php if(isset($this->breadcrumbs)):?>
								<?php
									if(Yii::app()->user->isGuest) {
										$this->widget('application.widgets.NBreadcrumbs', array(
											'links'=>$this->breadcrumbs,
											'htmlOptions' => array(
												'class' => 'breadcrumb',
											),
											'homeLink' => '<li><a href="'.Yii::app()->controller->createUrl('/site/login').'"><i class="icon-home icon-white"></i>Home</a></li>',
										));
									} else {
										$this->widget('application.widgets.NBreadcrumbs', array(
											'links'=>$this->breadcrumbs,
												'htmlOptions' => array(
												'class' => 'breadcrumb',
											),
											'homeLink' => '<li><a href="'.Yii::app()->controller->createUrl('/site/index').'"><i class="icon-home icon-white"></i>Home</a></li>',
									));
									}?><!-- breadcrumbs -->
							<?php endif?>
							</li>
						</ul>
						<ul class="nav pull-right">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-list icon-white"></i>KDE Links <b class="caret-up"></b></a>
								<ul id="global-nav" class="dropdown-menu bottom-up"></ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<footer class="Neverland">
				Maintained by <a href="http://go.kde.org/systickets/">KDE Sysadmin.</a> Design by <a href="mailto:kde-www@kde.org">KDE Webteam.</a><br>
				KDE<sup>&reg;</sup> and <a href="//www.kde.org/media/images/trademark_kde_gear_black_logo.png">the K Desktop Environment<sup>&reg;</sup> logo</a>
				are registered trademarks of <a title="Homepage of the KDE non-profit Organization" href="http://ev.kde.org/">KDE e.V.</a> |
				<a href="http://www.kde.org/community/whatiskde/impressum.php">Legal</a>
			</footer>
		</div>
	</div><!-- container -->
</body>
</html>