protected/controllers/RegistrationController.php
<?php
require('protected/vendors/recaptcha/autoload.php');
require('protected/vendors/MaxMind-DB-Reader/autoload.php');

use ReCaptcha\ReCaptcha;
use MaxMind\Db\Reader as MaxMindReader;

class RegistrationController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny', // Currently logged in users may not register, that does not make sense
				'actions' => array('index', 'enterDetails', 'confirm'),
				'users' => array('@'),
			),
			array('allow', // Allow users not yet logged in to register accounts
				'actions' => array('index', 'enterDetails', 'confirm'),
				'users' => array('*'),
			),
			array('allow', // Allow sysadmins to see pending registrations, and view or delete them
				'actions' => array('list', 'view', 'update', 'delete'),
				'roles' => array('sysadmins'),
			),
			array('deny',  // Any other action is denied
				'users' => array('*'),
			),
		);
	}

	public function actionIndex()
	{
		// If they have confirmed they accept our terms, mark them as accepted
		if( isset($_POST['confirmAcceptance']) && isset($_POST['continue']) ) {
			Yii::app()->user->setState('registerTermsAccepted', 'confirmed');
		}
		// If they have already accepted our terms, do not reprompt them
		if( Yii::app()->user->getState('registerTermsAccepted') == 'confirmed' ) {
			$this->redirect( array('enterDetails') );
		}
		// Make sure they are not an attempted spammer
		if( $this->performSpamCheck() ) {
			throw new CHttpException(403, "Client rejected by automatic spammer detection system");
		}
		if( $this->performIpBlacklistCheck() ) {
			throw new CHttpException(403, "Access Denied: Internet Service Provider blacklisted due to abuse. Please email sysadmin@kde.org to register an account.");
		}

		/**
		 * Check referer during the registration process to be able to show the user
		 * the page he is coming from and be able to redirect him at the end of the
		 * registration process.
		 */
		$refererHelper = new SiteReferer();
		$refererHelper->checkReferer();

		$this->render('index');
	}

	public function actionEnterDetails()
	{
		// Make sure they have accepted our terms....
		if( Yii::app()->user->getState('registerTermsAccepted') != 'confirmed' ) {
			$this->redirect( array('index') );
		}

		// Have they tried to register before?
		if( Yii::app()->user->getState('sentRegistration') == 'yes' ) {
			throw new CHttpException(403, 
				"Access Denied: Attempt to perform multiple registrations detected.\n" .
				"If you have received this notice and have not previously attempted to register, please email sysadmin@kde.org for further assistance."
			);
		}

		$model = new Token('register');

		// Maybe they have provided the needed information, in which case we need to act on it...
		if( isset($_POST['Token']) ) {
			$model->type = Token::TypeRegisterAccount;
			$model->attributes = $_POST['Token'];
			if( $this->performSpamCheck($model->mail) ) {
				Yii::app()->user->setState('sentRegistration', 'yes');
				throw new CHttpException(403, "Client rejected by automatic spammer detection system");
			}
			if( $this->performCaptchaCheck() ) {
				throw new CHttpException(403, "CAPTCHA Incorrect. Please go back and try again. If the CAPTCHA is not visible please disable all privacy and adblocker browser addons.");
			}
			if( $this->performIpBlacklistCheck() ) {
				Yii::app()->user->setState('sentRegistration', 'yes');
				throw new CHttpException(403, "Access Denied: Internet Service Provider blacklisted due to abuse. Please email sysadmin@kde.org to register an account.");
			}
			if( $this->performAbusiveClientCheck() ) {
				Yii::app()->user->setState('sentRegistration', 'yes');
				throw new CHttpException(403, "Client rejected by anti-spam identification measures");
			}
			if( $model->save() ) {
				$this->sendEmail($model->mail, '/mail/confirmRegistration', array('model' => $model));
				$this->render('confirmationSent', array('model' => $model));
				Yii::app()->user->setState('sentRegistration', 'yes');
				Yii::app()->end();
			}
		}

		$this->render('enterDetails', array(
			'model' => $model,
		));
	}

	public function actionConfirm($id, $token)
	{
		// Ensure the provided registration confirmation is valid
		$tokenModel = Token::model()->findByAttributes( array('id' => $id, 'type' => Token::TypeRegisterAccount, 'token' => $token) );
		if( !$tokenModel instanceof CActiveRecord ) {
			throw new CHttpException(404, 'The given validation could not be confirmed, please contact the site administrator.');
		}

		// Prepare the user which we will be finalising
		$model = new User('register');
		$knownData = $tokenModel->getAttributes( array('uid', 'givenName', 'sn', 'mail') );
		$model->setAttributes( $knownData, false ); // Copy unsafe values as well as this is internally stored

		// Maybe we have a submission to handle?
		if( isset($_POST['User']) ) {
			// Assign the inbound data
			$model->attributes = $_POST['User'];
			// Set the DN the new user will be created in
			$model->setDnByParent( Yii::app()->params['registrationUnit'] );
			// Try to create the user now. If the username/password is bad then it will fail
			if( $model->save() ) {
				// Creation succeeded, so cleanup....
				$tokenModel->delete();
				// Inform the site administrator of the account creation
				//$this->sendEmail(Yii::app()->params['registerNotify'], '/mail/notifyRegistration', array('model' => $model));
				// Give the user an email with their account details
				$this->sendEmail($model->mail, '/mail/notifyUserOfAccount', array('model' => $model));
				// Give the user a page informing them of their account details
				$this->render('complete', array('model' => $model));
				Yii::app()->end();
			}
		}

		$this->render('confirm', array(
			'model' => $model,
		));
	}

	public function actionList()
	{
		$model = new Token('search');
		if( isset($_GET['Token']) ) {
			$model->attributes = $_GET['Token'];
		}

		// Setup our list, including search support
		$criteria = new CDbCriteria;
		$criteria->compare('type', Token::TypeRegisterAccount);
		$criteria->compare('givenName', $model->givenName, true);
		$criteria->compare('sn', $model->sn, true);
		$criteria->compare('mail', $model->mail, true);
		$dataProvider = new CActiveDataProvider($model, array(
			'criteria' => $criteria,
			'pagination' => array('pageSize' => 20),
		));

		$this->render('list', array(
			'model' => $model,
			'dataProvider' => $dataProvider,
		));
	}

	public function actionView($id)
	{
		$model = $this->loadModel($id);

		if( isset($_POST['resendConfirmation']) ) {
			$this->sendEmail($model->mail, '/mail/confirmRegistration', array('model' => $model));
			Yii::app()->user->setFlash('success', 'Registration confirmation has been resent.');
		}

		$this->render('view', array(
			'model' => $model,
		));
	}

	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);
		$model->setScenario('register');

		if( isset($_POST['Token']) ) {
			$model->attributes = $_POST['Token'];
			if( $model->save() ) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
			'model' => $model,
		));
	}

	public function actionDelete($id)
	{
		$model = $this->loadModel($id);

		if( isset($_POST['confirmDeletion']) && isset($_POST['deleteAccount']) ) {
			if( $model->delete() ) {
				$this->redirect( array('list') );
			}
		}

		$this->render('delete', array(
			'model' => $model,
		));
	}

	protected function performSpamCheck($email = "")
	{
		// Is this a particular email address we shouldn't be accepting?
		// Does this address contain 'friv'? The name appears to be common in abused addresses
		if( strpos( $email, "friv", 0 ) !== false ) {
			return true;
		}
		// Does this address contain 'needhelp0x'? The name appears to be common in abused addresses
		if( strpos( $email, "needhelp0x", 0 ) !== false ) {
			return true;
		}

		// Address of the API we are using
		$query = "http://www.stopforumspam.com/api";
		// We want php serialized data
		$query .= "?f=serial";
		// Add email address and ip address parameters if we have them...
		if( $email != "" ) {
			$query .= "&email=" . trim($email);
		}
		// Add the ip address
		$query .= "&ip=" . Yii::app()->request->userHostAddress;

		// Perform the query...
		$result = @file_get_contents($query);

		// if we have network issues, let him through.
		if( $result === false ) {
			return false;
		}

		// Decode the data we recieved
		$result = unserialize($result);

		// if the query failed, permit the request
		if( $result["success"] != 1 ) {
			return false;
		}

		// If there is a greater than 80% the ip address is used by spammers, reject the request
		if( isset($result["ip"]["confidence"] ) && $result["ip"]["confidence"] > 80 ) {
			return true;
		}

		// If the email address has been used to spam anywhere, reject the request
		if( $email != "" && isset($result["email"]["confidence"]) && $result["email"]["confidence"] > 0 ) {
			return true;
		}

		// let everyone through.
		return false;
	}

	protected function performCaptchaCheck()
	{
		$secret = Yii::app()->params['recaptcha-secret'];
		$recaptcha = new ReCaptcha($secret);
		$resp = $recaptcha->verify(
			Yii::app()->request->getPost('g-recaptcha-response'),
			Yii::app()->request->userHostAddress
		);

		if( !$resp->isSuccess() ) {
			return true;
		}

		return false;
	}

	protected function performIpBlacklistCheck()
	{
		$userIp = Yii::app()->request->userHostAddress;

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// Page action renders "static" pages stored under 'protected/views/site/pages'
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		// Note: finer grained access control wrt profile/contact details/avatar/ssh key/password changing is done at action level
		return array(
			array('deny',  // Everyone who is authenticated cannot initiate a password reset
				'actions' => array('passwordReset', 'performPasswordReset'),
				'users' => array('@'),
			),
			array('allow',  // Everything else is permitted
				'users' => array('*'),
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		$model = new LoginForm;
		$this->render('index', array('model' => $model));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		$error = Yii::app()->errorHandler->error;
		if( $error ) {
			if(Yii::app()->request->isAjaxRequest) {
				echo $error['message'];
			} else {
				$this->render('error', $error);
			}
		}
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model = new LoginForm;

		// If they are already logged in, they cannot login again...
		if( !Yii::app()->user->isGuest ) {
			$this->redirect( Yii::app()->homeUrl );
		}

		// Handle a AJAX validation request if we have one
		if( isset($_POST['ajax']) && $_POST['ajax'] === 'login-form' ) {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// Handle input
		if( isset($_POST['LoginForm']) ) {
			$model->attributes = $_POST['LoginForm'];
			// Validate the login and redirect to the previous page if valid
			if( $model->validate() && $model->login() ) {
				$return = Yii::app()->user->getReturnUrl( array('/people/view', 'uid' => Yii::app()->user->id) );
				$this->redirect( $return );
			} else if( $model->validate() ) {
				$this->redirect( array('loginTwoFactor', 'username' => $model->username) );
			}
		}

		// Display the login form
		$this->render('login', array('model' => $model));
	}

	/**
	 * Performs two factor authentication if necessary
	 */
	public function actionLoginTwoFactor( $username )
	{
		$model = new LoginForm('twoFactor');
		$model->username = $username;

		$entry = AccountSecurity::model()->retrieveAccount($username);
		if( $entry->event_count >= 5 ) {
			throw new CHttpException(403, 'Two-factor authentication attempts have failed too many times recently for this account, please try again later. If you have lost your grid, please perform a password reset.');
		}

		// Handle input
		if( isset($_POST['LoginForm']) ) {
			$model->attributes = $_POST['LoginForm'];
			// Validate the login and redirect to the previous page if needed
			if( $model->validate() && $model->login() ) {
				$return = Yii::app()->user->getReturnUrl( array('/people/view', 'uid' => Yii::app()->user->id) );
				$this->redirect( $return );
			} else {
				// Flag an attempt on this account
				$entry->save();
			}
		}

		// Display the two-factor authentication form
		$gridPosition = Yii::app()->tokenGrid->getRandomGridPosition( $model->username );
		$this->render('loginTwoFactor', array('model' => $model, 'gridPosition' => $gridPosition));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect( Yii::app()->homeUrl );
	}

	public function actionPasswordReset()
	{
		$model = new Token('reset');
		$model->type = Token::TypeResetPassword;

		// Handle input
		if( isset($_POST['Token']) ) {
			$model->attributes = $_POST['Token'];
			// Validate the username and email address they have provided...
			if( $model->save() ) {
				$this->sendEmail($model->mail, '/mail/passwordReset', array('model' => $model));
				$this->render('passwordResetPending', array('model' => $model));
				Yii::app()->end();
			}
		}

		// Display the password reset form
		$this->render('passwordReset', array('model' => $model));
	}

	public function actionPerformPasswordReset($uid, $token)
	{
		// Load the token first - if that is invalid then they cannot reset the password
		$entry = Token::model()->findByAttributes( array('uid' => $uid, 'type' => Token::TypeResetPassword, 'token' => $token) );
		if( !$entry instanceof Token ) {
			throw new CHttpException(404, 'The given token could not be authenticated.');
		}

		// Load the user now
		$filter = Net_LDAP2_Filter::create('uid', 'equals', $entry->uid);
		$model = User::model()->findFirstByFilter($filter);
		if( !$model instanceof User ) {
			throw new CHttpException(404, 'The specified user could not be found.');
		}
		$model->setScenario('changePassword');

		// Handle the actual password reset
		if( isset($_POST['User']) ) {
			$model->attributes = $_POST['User'];
			$model->removeAttribute('twoFactorAuthentication');
			if( $model->save() ) {
				$entry->delete();
				$this->render('passwordResetSuccessful', array('model' => $model));
				Yii::app()->end();
			}
		}

		// Display the new password form
		$this->render('performPasswordReset', array('model' => $model));
	}
}

protected/views/site/_login.php
<div class="form well">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id' => 'login-form',
	'action' => array('/site/login'),
	'enableClientValidation' => false,
)); ?>

	<div class="row-fluid">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->error($model, 'authentication'); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Login', array('class' => 'btn btn-primary')); ?>
		<?php echo CHtml::link('Reset Password', array('passwordReset')); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/site/error.php
<?php
$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="alert alert-error">
<?php echo nl2br(CHtml::encode($message)); ?>
</div>

protected/views/site/index.php
<?php $this->pageTitle=Yii::app()->name; ?>
<div class="hero-unit">
	<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

	<p class="lead">Welcome to the home of the KDE Identity system. </p>
	<p>
		KDE Identity is the central account manager for the KDE.org infrastructure.
		<br />
		A KDE Identity account allows unified access to most KDE.org websites, and commit access to the various code repositories.
	</p>

	<?php if( Yii::app()->user->isGuest ) { ?>
		<h2>Login</h2>
		<?php $this->renderPartial('_login', array('model' => $model));
	} ?>
</div>

protected/views/site/login.php
<?php
$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1>Login</h1>

<p>Not registered yet? You can begin registration <?php echo CHtml::link('here', array('/registration/index')); ?>.</p>

<?php $this->renderPartial('_login', array('model' => $model)); ?>

protected/views/site/loginTwoFactor.php
<?php
$this->pageTitle=Yii::app()->name . ' - Two-Factor Authentication';
$this->breadcrumbs=array(
	'Two-Factor Authentication',
);
?>

<h1>Two-Factor Authentication</h1>

<p>Your KDE Identity account is currently protected with Two-Factor Authentication, please complete it to login.</p>

<div class="form well">
<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'loginTwoFactor-form',
	'enableClientValidation' => false,
)); ?>

	<p>Please enter the token from position '<?php echo CHtml::encode($gridPosition); ?>'.</p>
	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'token'); ?>
		<?php echo $form->textField($model, 'token'); ?>
		<?php echo $form->error($model, 'token'); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'password'); ?>
		<?php echo $form->passwordField($model, 'password'); ?>
		<?php echo $form->error($model, 'password'); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->error($model, 'authentication'); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Complete Login', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/site/passwordReset.php
<?php
$this->breadcrumbs = array(
	'Reset Password',
	'Begin',
);

$this->menu = array();
?>

<h1>Reset Password</h1>

<p>Please fill out the details below to allow your account password to be reset.</p>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'passwordReset-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'uid'); ?>
		<?php echo $form->textField($model, 'uid'); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'mail'); ?>
		<?php echo $form->textField($model, 'mail'); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Request Password Reset', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/site/passwordResetPending.php
<?php
$this->breadcrumbs = array(
	'Reset Password',
	'Awaiting Confirmation'
);

$this->menu = array();
?>

<h1>Password Reset Awaiting Confirmation</h1>

<p>Details on how to reset your password have now been sent to the email address you specified.</p>

protected/views/site/passwordResetSuccessful.php
<?php
$this->breadcrumbs=array(
	'Password Reset',
	'Completed',
);

$this->menu = array();
?>

<h1>Password Reset Successful</h1>

<p>Your account password has been reset successfully, you may now <?php echo CHtml::link('login', array('site/login')); ?>.</p>

protected/views/site/performPasswordReset.php
<?php
$this->breadcrumbs = array(
	'Reset Password',
	'Enter New Password',
);

$this->menu = array();
?>

<h1>Reset Password</h1>

<p>Please fill out the details below to allow your account password to be reset.</p>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'passwordReset-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'newPassword'); ?>
		<?php echo $form->passwordField($model, 'newPassword', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'confirmNewPassword'); ?>
		<?php echo $form->passwordField($model, 'confirmNewPassword', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Change Password', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>