protected/controllers/PeopleController.php
<?php

class PeopleController extends Controller
{
	/**
	 * Use the appropriate layout
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		// Note: finer grained access control wrt profile/contact details/avatar/ssh key/password changing is done at action level
		return array(
			array('allow',  // Everyone who is authenticated may list people and view them (including avatars)
				'actions' => array('index', 'view', 'viewAvatar'),
				'users' => array('@'),
			),
			array('allow', // Everyone is allowed to change their profile, contact details, avatar and password
				'actions' => array('editProfile', 'editContactDetails', 'editEmailAddresses', 'verifyEmail', 'editAvatar', 'changePassword', 'twoFactorAuthentication'),
				'users' => array('@'),
			),
			array('allow', // Developers, Disabled Developers and Sysadmins are allowed to change SSH keys
				'actions' => array('editKeys'),
				'roles' => array('developers', 'disabled-developers', 'sysadmins'),
			),
			array('allow', // Creating, Deleting, Moving and Locking is for Sysadmins only
				'actions' => array('create', 'delete', 'move', 'toggleLock'),
				'roles' => array('sysadmins'),
			),
			array('deny',  // If not permitted above - access is denied...
				'users' => array('*'),
			),
		);
	}

	/**
	 * Show the list of people
	 */
	public function actionIndex()
	{
		// Create the model instance we will be using for searches....
		$model = new User('search');
		if( isset($_GET['User']) ) {
			$model->attributes = $_GET['User'];
		}
		
		// Prepare the data provider - and apply a filter to it to ensure filters are applied
		$dataProvider = new SLdapDataProvider($model);
		$dataProvider->setFilterByModel($model, array('uid', 'cn', 'mail'));
		$dataProvider->setAttributesToLoad( array('uid', 'cn', 'mail') );

		$this->render('index', array(
			'dataProvider' => $dataProvider,
			'model' => $model,
		));
	}

	/**
	 * Create a new person
	 */
	public function actionCreate()
	{
		$model = new User;
		
		// Are we attempting to perform the create action?
		if( isset($_POST['User']) ) {
			// Assign the attributes
			$model->attributes = $_POST['User'];
			
			// Determine the DN we want to be under
			$parent = OrganisationalUnit::model()->findByDn( $_POST['User']['parentDn'] );
			if( $parent instanceof OrganisationalUnit ) {
				$model->setDnByParent($parent);
			}
			
			// Create the new person
			if( $model->save() ) {
				Yii::app()->user->setFlash('success', 'Person created.');
				$this->redirect(array('view', 'uid' => $model->uid));
			}
		}
		
		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Show a person's profile and contact details
	 */
	public function actionView($uid)
	{
		$model =  $this->loadModel($uid, array('pwdAccountLockedTime', '*'));

		$groupData = new CArrayDataProvider($model->groups->entries(), array('keyField' => false));
		$this->render('view', array(
			'model' => $model,
			'groupData' => $groupData,
		));
	}

	/**
	 * Return the Avatar image of the given person
	 */
	public function actionViewAvatar($uid)
	{
		header('Content-type: octet-stream');
		header('Content-Transfer-Encoding: binary');
		$model = $this->loadModel($uid);
		if( isset($model->jpegPhoto) ) {
			echo $model->jpegPhoto;
		} else {
			$path = Yii::app()->basePath . DIRECTORY_SEPARATOR . "data" . DIRECTORY_SEPARATOR . "default-avatar.png";
			echo file_get_contents($path);
		}
	}

	/**
	 * Delete an existing person
	 */
	public function actionDelete($uid)
	{
		$model = $this->loadModel($uid);
		$model->setScenario('delete');

		// Deleting yourself is not a good idea
		if($model->dn == Yii::app()->user->dn) {
			throw new CHttpException(403, 'You are not permitted to commit suicide.');
		}

		if( isset($_POST['confirmDeletion']) && isset($_POST['deleteAccount']) ) {
			if( $model->delete() ) {
				Yii::app()->user->setFlash('success', 'Person deleted.');
				$this->redirect( array('index') );
			}
		}

		$this->render('delete', array(
			'model' => $model,
		));
	}

	/**
	 * Edit the person's profile values
	 */
	public function actionEditProfile($uid)
	{
		$model = $this->loadModel($uid);
		$model->setScenario('editProfile');

		if( !Yii::app()->user->checkAccess('changeUserDetails', array('user' => $model)) && !Yii::app()->user->checkAccess('manageEvMembershipData', array('user' => $model)) ) {
			throw new CHttpException(403, 'You are not permitted to change the details of this person');
		}

		if( isset($_POST['User']) ) {
			// If we have the permission to, update the users username - and update their DN
			if( Yii::app()->user->checkAccess('changeUserUsername', array('user' => $model)) ) {
				$model->uid = $_POST['User']['uid'];
				$model->setDnByParent( $model->getParentDn() );
			}
			// If we have permission to update their KDE e.V. membership
			if( Yii::app()->user->checkAccess('manageEvMembershipData', array('user' => $model)) ) {
				$model->memberStatus = $_POST['User']['memberStatus'];
			}
			// Update all other attributes...
			$model->attributes = $_POST['User'];
			// Save the changes
			if( $model->save() ) {
				Yii::app()->user->setFlash('success', 'Profile updated.');
				$this->redirect( array('view', 'uid' => $model->uid) );
			}
		}

		$this->render('editProfile', array(
			'model' => $model,
		));
	}

	/**
	 * Edit the person's contact details
	 */
	public function actionEditContactDetails($uid)
	{
		$model = $this->loadModel($uid);
		$model->setScenario('editContactDetails');

		if( !Yii::app()->user->checkAccess('changeUserDetails', array('user' => $model)) ) {
			throw new CHttpException(403, 'You are not permitted to change the details of this person.');
		}

		if( isset($_POST['User']) ) {
			$model->attributes = $_POST['User'];
			if( $model->save() ) {
				Yii::app()->user->setFlash('success', 'Contact details updated.');
				$this->redirect( array('view', 'uid' => $model->uid) );
			}
		}
		
		$this->render('editContactDetails', array(
			'model' => $model,
		));
	}

	public function actionEditEmailAddresses($uid)
	{
		$model = $this->loadModel($uid);
		$model->setScenario('editContactDetails');

		if( !Yii::app()->user->checkAccess('changeUserDetails', array('user' => $model)) ) {
			throw new CHttpException(403, 'You are not permitted to change the details of this person.');
		}

		// Setup the Token which we use to ensure the addresses submitted to us are valid (and other things)
		$token = new Token;
		if( isset($_POST['Token']) ) {
			$token->uid = $model->uid;
			$token->mail = $_POST['Token']['mail'];
			$token->type = Token::TypeVerifyAddress;
		}

		if( isset($_POST['action']) && isset($_POST['Token']) && $token->validate() ) {
			// Which action is being processed?
			$action = $_POST['action'];

			// Maybe we are changing the primary address?
			if( $action == 'primary' ) {
				// Try to make the given address the primary. The model will refuse if it is not permitted
				if( $model->setPrimaryEmailAddress($token->mail) && $model->save() ) {
					Yii::app()->user->setFlash('success', 'Primary email address changed.');
				}
			}

			// Maybe we are resending a verification?
			if( $action == 'resend' ) {
				// Find the potential address....
				$entry = Token::model()->findByAttributes( array('uid' => $model->uid, 'type' => Token::TypeVerifyAddress, 'mail' => $token->mail) );
				if( $entry instanceof CActiveRecord ) {
					// Send the mail...
					$this->sendEmail($entry->mail, '/mail/verifyEmail', array('entry' => $entry, 'model' => $model));
					Yii::app()->user->setFlash('success', 'Address verification resent.');
				}
			}

			// Maybe we are removing an address?
			if( $action == 'remove' ) {
				// Try to remove the given address. The model will refuse if it is not permitted
				if( $model->removeEmailAddress($token->mail) ) {
					Yii::app()->user->setFlash('success', 'Email address removed.');
				}
			}

			// Maybe we are adding an address, and if so, it is to ourselves?
			if( $action == 'add' && Yii::app()->user->dn == $model->dn ) {
				// Save the new pending email - if successful send an email regarding that
				$token->setScenario('verify');
				if( $token->save() ) {
					$this->sendEmail($token->mail, '/mail/verifyEmail', array('entry' => $token, 'model' => $model));
					Yii::app()->user->setFlash('success', 'Email address will be added once verification is completed.');
				}
			}
			// If we are not adding to ourselves, then we do not need verification
			if( $action == 'add' && Yii::app()->user->dn != $model->dn ) {
				// If it is not ourselves then we can immediately add it
				$model->addAttribute("secondaryMail", $token->mail);
				if( $model->save() ) {
					Yii::app()->user->setFlash('success', 'Email address added.');
				}
			}

			// If we have a flash then assume success and clear the email address
			if( Yii::app()->user->getFlashes(false) !== array() ) {
				unset($token->mail);
			}
		}

		$emailDataProvider = new CArrayDataProvider($model->emailAddressData);
		$this->render('editEmailAddresses', array(
			'model' => $model,
			'token' => $token,
			'emailDataProvider' => $emailDataProvider,
		));
	}

	public function actionVerifyEmail($uid, $token)
	{
		// Load the user
		$model = $this->loadModel($uid);
		$model->setScenario('editContactDetails');

		// Lookup the given token, and verify it
		$entry = Token::model()->findByAttributes( array('type' => Token::TypeVerifyAddress, 'uid' => $model->uid, 'token' => $token) );
		if( !$entry instanceof CActiveRecord ) {
			throw new CHttpException(404, 'The given token could not be validated.');
		}

		// We now have a valid token, add the new address

protected/views/people/changePassword.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Change Password',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Change Password for <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php if( Yii::app()->user->dn == $model->dn ) { ?>
		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'currentPassword'); ?>
			<?php echo $form->passwordField($model, 'currentPassword', array('size' => 60, 'maxlength' => 128)); ?>
		</div>
	<?php } ?>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'newPassword'); ?>
		<?php echo $form->passwordField($model, 'newPassword', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'confirmNewPassword'); ?>
		<?php echo $form->passwordField($model, 'confirmNewPassword', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Change Password', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/people/create.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	'Create',
);
?>

<h1>Create Person</h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row-fluid-fluid">
		<?php echo $form->labelEx($model, 'uid'); ?>
		<?php echo $form->textField($model, 'uid', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'givenName'); ?>
		<?php echo $form->textField($model, 'givenName', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'sn'); ?>
		<?php echo $form->textField($model, 'sn', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'mail'); ?>
		<?php echo $form->textField($model, 'mail', array('size' => 60, 'maxlength' => 128)); ?>
	</div>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'parentDn'); ?>
		<?php echo $form->dropDownList($model, 'parentDn', CHtml::listData(OrganisationalUnit::model()->findByFilter(null), 'dn', 'dn'), array('empty'=> 'Select Parent Unit')); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Create', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/people/delete.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Delete',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Delete Account of <?php echo CHtml::encode($model->cn); ?></h1>

<div class="alert">
	<h4 class="alert-heading">Warning!</h4>
	The account of '<?php echo CHtml::encode($model->uid); ?>' will be deleted if you proceed.
</div>

<div class="form">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>
	<div class="well">
		<p>
			<?php echo CHtml::checkbox('confirmDeletion') ?>
			Confirm account deletion
		</p>
		<div class="row-fluid buttons">
			<?php echo CHtml::submitButton('Delete Account', array('name' => 'deleteAccount', 'class' => 'btn btn-primary')); ?>
		</div>
	</div>
	
<?php $this->endWidget(); ?>

</div>

protected/views/people/editAvatar.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Change Avatar',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Change Avatar of <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">
	<div class="row-fluid">
		<div class="span12">
			<?php $form = $this->beginWidget('CActiveForm', array(
				'id' => 'person-form',
				'enableAjaxValidation' => false,
				'htmlOptions' => array('enctype' => 'multipart/form-data'),
			)); ?>
			<div class="row-fluid">
				<div class="span9">
					<div class="row-fluid">
						<?php echo $form->labelEx($model, 'jpegPhoto'); ?>
						<?php echo $form->error($model, 'jpegPhoto'); ?>
						<?php echo $form->fileField($model, 'jpegPhoto'); ?>
					</div>
					<div class="row-fluid buttons">
						<?php echo CHtml::submitButton('Upload Avatar', array('name' => 'uploadAvatar', 'class' => 'btn btn-primary')); ?>
					</div>
				</div>
				<div class="span3">
					<?php echo CHtml::image( CHtml::normalizeUrl(array('viewAvatar', 'uid' => $model->uid)), '', array('class' => 'thumbnail') ); ?>
					<br />
					<?php if( isset($model->jpegPhoto) && !$model->jpegPhoto instanceof CUploadedFile ) { ?>
						<?php echo CHtml::submitButton('Clear Avatar', array('name' => 'clearAvatar', 'class' => 'btn')); ?>
					<?php } ?>
				</div>
				<div class="clearfix"></div>
				<?php $this->endWidget(); ?>
			</div>
		</div>
	</div>
</div>

protected/views/people/editContactDetails.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Edit Contact Details',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Edit Contact Details for <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Please ensure you save your contact details after adding details.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php $this->widget('application.widgets.MultiEdit', array(
		'model' => $model,
		'attribute' => 'homePhone',
		'editorHtmlOptions' => array('size' => 60),
	)); ?>

	<?php $this->widget('application.widgets.MultiEdit', array(
		'model' => $model,
		'attribute' => 'homePostalAddress',
		'editorType' => 'textarea',
		'editorHtmlOptions' => array('cols' => 60, 'rows' => 3),
	)); ?>

	<?php $this->widget('application.widgets.MultiEdit', array(
		'model' => $model,
		'attribute' => 'labeledURI',
		'editorHtmlOptions' => array('size' => 60),
	)); ?>

	<?php $this->widget('application.widgets.MultiEdit', array(
		'model' => $model,
		'attribute' => 'ircNick',
		'editorHtmlOptions' => array('size' => 60),
	)); ?>

	<?php $this->widget('application.widgets.MultiEdit', array(
		'model' => $model,
		'attribute' => 'jabberID',
		'editorHtmlOptions' => array('size' => 60),
	)); ?>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Update Contact Details', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/people/editEmailAddresses.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Manage Email Addresses',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Manage Email Addresses for <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'emailAddress-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">The primary email address cannot be removed as all accounts must have a email address associated with them.</p>

	<?php $this->widget('application.components.NeverGridView', array(
		'id' => 'emailAddress-grid',
		'dataProvider' => $emailDataProvider,
		'template' => '{items}{pager}',
		'columns'=> array(
			'mail:email:Email Address',
			array(
				'type' => 'raw',
				'value'=> 'EmailHelper::showVerification($data);',
				'htmlOptions' => array('style' => 'width: 150px;'),
			),
			array(
				'type' => 'raw',
				'value'=> 'EmailHelper::showDelete($data);',
				'htmlOptions' => array('style' => 'width: 150px;'),
			),
		),
	)); ?>

<?php $this->endWidget(); ?>

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'emailAddress-form',
	'enableAjaxValidation' => false,
)); ?>

	<?php echo $form->labelEx($token, 'mail', array('label' => 'Add Email Address')); ?>
	<?php echo $form->textField($token, 'mail', array('size' => 60, 'maxlength' => 128)); ?>
	<?php echo $form->error($token, 'mail'); ?>

	<?php echo CHtml::hiddenField('action', 'add'); ?>
	<?php echo CHtml::submitButton('Add', array('class' => 'btn btn-primary')); ?>

<?php $this->endWidget(); ?>

</div>

protected/views/people/editKeys.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Manage SSH Keys',
);

$this->menu = $this->generateMenu($model);

Yii::app()->clientScript->registerScript("disableCheckAll", "$('input.select-on-check-all').hide();", CClientScript::POS_LOAD);
?>

<h1>Manage SSH Keys of <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
	'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>

	<p class="alert alert-info">Please be aware that SSH Key changes will be synced to KDE infrastructure automatically, and should be active within 1 minute.</p>

	<div class="row-fluid">
		<?php $this->widget('application.components.NeverGridView', array(
			'id' => 'sshkey-grid',
			'selectableRows' => 2,
			'dataProvider' => $dataProvider,
			'template' => '{items}{pager}',
			'columns'=> array(
				array(
					'class' => 'CCheckBoxColumn',
					'id' => 'selectedKeys'
				),
				'type:text:Type',
				'fingerprint:text:Fingerprint',
				'comment:text:Comment',
			),
		)); ?>
		<?php
			if( $dataProvider->itemCount > 0 ) {
				echo CHtml::submitButton('Remove Selected Keys', array('name' => 'removeKeys', 'class' => 'btn'));
			}
		?>
	</div>

	<hr />
	<h3>Add New SSH Key</h3>
	<div class="row-fluid">
		<?php echo $form->error($model, 'sshKeysAdded'); ?>
		<?php echo $form->fileField($model, 'sshKeysAdded'); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Upload Keys', array('name' => 'uploadKeys', 'class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/people/editProfile.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Edit Profile',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Edit Profile of <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php if( Yii::app()->user->checkAccess('changeUserUsername', array('user' => $model)) ) { ?>
		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'uid'); ?>
			<?php echo $form->textField($model, 'uid', array('size' => 60, 'maxlength' => 128)); ?>
		</div>
	<?php } ?>

	<?php if( Yii::app()->user->checkAccess('changeUserDetails', array('user' => $model)) ) { ?>
		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'givenName'); ?>
			<?php echo $form->textField($model, 'givenName', array('size' => 60, 'maxlength' => 128)); ?>
		</div>

		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'sn'); ?>
			<?php echo $form->textField($model, 'sn', array('size' => 60, 'maxlength' => 128)); ?>
		</div>

		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'dateOfBirth'); ?>
			<?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
				'model' => $model,
				'attribute' => 'dateOfBirth',
				'options' => array(
					'showAnim' => 'fold',
					'dateFormat' => 'dd/mm/yy',
					'changeYear' => true,
					'yearRange' => 'c-120:c+0',
				),
				'htmlOptions' => array('size' => 60),
			)); ?>
		</div>

		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'gender'); ?>
			<?php echo $form->dropDownList($model, 'gender', $model->validGenders(), array('empty'=> 'Not set')); ?>
		</div>

		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'timezoneName'); ?>
			<?php echo $form->dropDownList($model, 'timezoneName', $model->preppedTimezones(), array('empty'=> 'Not set')); ?>
		</div>
	<?php } ?>

	<?php if( Yii::app()->user->checkAccess('manageEvMembershipData', array('user' => $model)) ) { ?>
		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'memberStatus'); ?>
			<?php echo $form->dropDownList($model, 'memberStatus', $model->validMemberStatus()); ?>
		</div>
	<?php } ?>

	<?php if( Yii::app()->user->checkAccess('changeUserEvDetails', array('user' => $model)) ) { ?>
		<div class="row-fluid">
			<?php echo $form->labelEx($model, 'evMail'); ?>
			<?php echo $form->dropDownList($model, 'evMail', $model->validEmailAddresses()); ?>
		</div>
	<?php } ?>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Update Profile', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/people/index.php
<?php
$this->breadcrumbs = array('People');
$this->menu = array( array('label' => 'Create Person', 'url' => array('create'), 'visible' => Yii::app()->user->checkAccess('sysadmins') ) );
?>

<h1>People</h1>
<p>Shown below are both full and partial matches against the entered filter text. A maximum of 150 results can be shown at any one time.</p>
<hr/>
<?php $this->widget('application.components.NeverGridView', array(
	'id'=> 'person-grid',
	'dataProvider'=> $dataProvider,
	'filter'=> $model,
	'columns'=> array(
		array(
			'class' => 'LinkDataColumn',
			'name' => 'uid',
			'urlExpression'=> 'Yii::app()->createUrl("/people/view", array("uid" => $data->uid))',
		),
		'cn',
		'mail',
	),
)); ?>

protected/views/people/move.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Move (Change Parent Organisational Unit)',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Change Parent Organisational Unit of <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form well">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">This will change the Parent Organisational Unit for <?php echo CHtml::encode($model->cn); ?> which may affect LDAP based logins.</p>
	<?php echo $form->errorSummary($model); ?>

	<div class="row-fluid">
		<?php echo $form->labelEx($model, 'parentDn'); ?>
		<?php echo $form->dropDownList($model, 'parentDn', CHtml::listData(OrganisationalUnit::model()->findByFilter(null), 'dn', 'dn'), array('empty'=> 'Select Parent Unit')); ?>
	</div>

	<div class="row-fluid buttons">
		<?php echo CHtml::submitButton('Move Account', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div>

protected/views/people/toggleLock.php
<?php
$this->breadcrumbs = array(
	'People' => array('index'),
	$model->cn => array('view', 'uid' => $model->uid),
	'Lock/Unlock account',
);

$this->menu = $this->generateMenu($model);
?>

<h1>Lock/Unlock Account of <?php echo CHtml::encode($model->cn); ?></h1>

<div class="form">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'person-form',
	'enableAjaxValidation' => false,
)); ?>

	<p class="alert alert-info">Temporary locks are performed automatically when too many invalid password attempts are made, and will expire automatically.</p>
	<p><strong>Account Status:</strong> <?php echo CHtml::encode($model->accountStatus); ?>.</p>

	<div class="row-fluid buttons">
		<?php 
			if( $model->accountStatus != User::AccountUnlocked ) {
				echo CHtml::submitButton('Unlock Account', array('name' => 'unlockAccount', 'class' => 'btn btn-primary'));
			}
			if( $model->accountStatus != User::AccountPermanentLocked ) {
				echo CHtml::submitButton('Lock Account Infinitely', array('name' => 'lockAccount', 'class' => 'btn btn-primary'));
			}
		?>
	</div>

<?php $this->endWidget(); ?>

</div>